# Generated by Django 5.2 on 2025-05-17 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
            },
        ),
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=70)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.area"
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo",
                "verbose_name_plural": "Conteúdos",
            },
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField()),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "conteudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.conteudo"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Perguntas",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        max_length=7,
                    ),
                ),
                ("pontuacao", models.FloatField(default=0)),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.area"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizConteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.conteudo"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quiz"
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo do Quiz",
                "verbose_name_plural": "Conteúdos do Quiz",
            },
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.CharField(max_length=50)),
                ("correta", models.BooleanField()),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.pergunta"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Respostas",
            },
        ),
        migrations.CreateModel(
            name="QuizPergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.pergunta"
                    ),
                ),
                (
                    "quiz_conteudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.quizconteudo",
                    ),
                ),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.resposta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta do Quiz",
                "verbose_name_plural": "Perguntas do Quiz",
            },
        ),
        migrations.AddConstraint(
            model_name="conteudo",
            constraint=models.UniqueConstraint(
                fields=("area", "nome"), name="unique_area_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizconteudo",
            constraint=models.UniqueConstraint(
                fields=("quiz", "conteudo"), name="unique_quiz_conteudo"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizpergunta",
            constraint=models.UniqueConstraint(
                fields=("quiz_conteudo", "pergunta"), name="unique_quiz_pergunta"
            ),
        ),
    ]
