# Generated by Django 5.2 on 2025-06-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizpergunta",
            name="resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.resposta",
            ),
        ),
    ]
