# Generated by Django 5.2 on 2025-06-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_quizpergunta_resposta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ranking",
            options={
                "ordering": ["-pontuacao"],
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
            },
        ),
        migrations.AlterField(
            model_name="ranking",
            name="pontuacao",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
